server {
    # Listen on 443 for SSL
    #ipv4 
    listen 443 ssl;
    #ipv6
    listen [::]:443 ssl;

    server_name mcamaren.42.fr; 

    # SSL Certificate Paths (matching the Dockerfile)
    # prooves the service identification and encrypts the data between the client and the server 
    ssl_certificate /etc/nginx/ssl/inception.crt;
    #decrypts the data and proves the ownership of the certificate
    ssl_certificate_key /etc/nginx/ssl/inception.key;

    # Supported Protocols
    # https protocols that the server will use to communicate securely with clients.    
    ssl_protocols TLSv1.2 TLSv1.3;

    #directorio raiz
    root /var/www/html;
    #archivo de inicio
    index index.php;


    #e.g. https://mcamaren.42.fr/blog?page=2
    # $uri → /blog
    # $args → page=2
    location / {
        try_files $uri $uri/ /index.php?$args;
    }



# location → defines how NGINX handles requests
# ~ → means regular expression match
# \.php$ → matches any URL ending in .php

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass wordpress:9000;
        #send request to php interpreter running in the wordpress container on port 9000
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}