[www]
; php processes will run as www-data:www-data
user = www-data
group = www-data

; port 9000, default fastcgi port
listen = 9000

; Set permissions for the socket (if using a socket instead of a port)
listen.owner = www-data
; Set the group for the socket
listen.group = www-data

; define how php handles incoming traffic 
pm = dynamic
; Set the maximum number of child processes to be created. This should be set based on the expected traffic and available resources of your server. For a small WordPress site, 5 is a reasonable starting point.
pm.max_children = 5
; Set the number of child processes to start with, and the minimum and maximum number of spare servers to keep available    
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3

; Optional but recommended: kills a worker after 500 requests to prevent memory leaks
pm.max_requests = 500

; This ensures your Docker environment variables are visible to PHP
clear_env = no